version: '3'
services:
  server:
    command: "nodemon -L -e js,mjs  --exec node --experimental-modules index.mjs"
    build:
      context: ./
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongo
    links:
      - redis
      - mongo
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
  mongo:
    image: "mongo"
    ports:
      - 27017:27017
    logging:
      driver: none
